Issue#110
mepox/fitbuddy pull request #119
Opened 2022-11-14 05:45 UTC by dmitriydb

## Summary 

1. The class `app.fitbuddy.jpa.entity.DefaultExercise` does not have `@RequiredArgsConstructor` Lombok annotation or the constructor with `id` and `name` parameters so it's kinda hard to create dummy instances for testing. 
I was thinking about extending it with another test class that has such constructor (decorator pattern) for testing purpose but maybe it's a bad idea
Is it possible to add all-args constructor to `DefaultExercise` and if it is could I open the corresponding issue?

2. What should the `NewUserService` bean do when `addDefaultExercises` method is invoked with appUserId null or negative value? I haven't write the corresponding tests yet

## Close issue(s) 
Close #110

2022-11-14 08:47 UTC, mepox commented
Hi @dmitriydb ! Thank you for your contribution again 👍 I appreciate you took your time to work on this.

> 1. The class `app.fitbuddy.jpa.entity.DefaultExercise` does not have `@RequiredArgsConstructor` Lombok annotation or the constructor with `id` and `name` parameters so it's kinda hard to create dummy instances for testing. 
I was thinking about extending it with another test class that has such constructor (decorator pattern) for testing purpose but maybe it's a bad idea
Is it possible to add all-args constructor to `DefaultExercise` and if it is could I open the corresponding issue?

I can't remember what was my reasoning to not use the `@RequiredArgsConstructor` on entities. However there are TestHelper classes in `/src/test/java/app/fitbuddy/testhelper/` to create mocks for entities.

> 2. What should the `NewUserService` bean do when `addDefaultExercises` method is invoked with appUserId null or negative value? I haven't write the corresponding tests yet

Good question, as I forget to add checks for the appUserId... 😅 I think the best would be to throw a new FitBuddyException for now with a message "Internal server error - appUserId is not correct"? Can you add these checks to the `NewUserService` please?

2022-11-14 09:52 UTC, dmitriydb commented
> However there are TestHelper classes in /src/test/java/app/fitbuddy/testhelper/ to create mocks for entities.

OK, refactored the test code to use your implementation instead of creation my own.
Also I've added isEqual methods into DefaultExerciseHelper.

> Can you add these checks to the NewUserService please
Done

2022-11-14 13:07 UTC, mepox commented on src/test/java/app/fitbuddy/testhelper/DefaultExerciseTestHelper.java
> +import app.fitbuddy.jpa.entity.Exercise;
Unused import in Line 5

2022-11-14 13:08 UTC, mepox commented on src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java
> +import org.junit.jupiter.api.BeforeEach;
Unused import in Line 9

2022-11-14 13:29 UTC, mepox commented on src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java
> +	}
We could shorten this part by using `@ParameterizedTest`. Then use `@NullSource` annotation to provide a null value and use `@ValueSource` to provide the exact values.

```
@ParameterizedTest
@NullSource
@ValueSource(ints = { -7 })
public void example(Integer input) { ...
```

2022-11-14 13:40 UTC, mepox requested changes
@dmitriydb Thanks for your previous refactor. 👍 

The PR looks good. I only found a few small issues, please see my comments.

Once you apply those changes, I will merge this PR 🎉  Thanks

2022-11-14 17:43 UTC, mepox requested changes

2022-11-14 17:43 UTC, mepox commented on src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java
> +import org.springframework.beans.factory.annotation.Value;
Unused import in Line 18

2022-11-14 17:47 UTC, mepox commented
@dmitriydb 
Unfortunately, I found an other unused import, see my comment. I guess you just added it now by mistake.

2022-11-15 04:01 UTC, dmitriydb commented
@mepox 
Sorry, I fixed that. Is it better now?
I hope you're not annoyed yet 😄  I have little experience with collaboration

I see you're separating import sections with empty line, I've tried to replicate that in `NewUserServiceTest` too.

2022-11-15 08:14 UTC, mepox approved these changes

2022-11-15 08:22 UTC, mepox commented
> @mepox Sorry, I fixed that. Is it better now? I hope you're not annoyed yet 😄 I have little experience with collaboration
> 
> I see you're separating import sections with empty line, I've tried to replicate that in `NewUserServiceTest` too.

@dmitriydb 
Thank you for your contribution and for applying the changes. 🥇  The PR looks good now, it will be merged soon. 🎉 

No worries, I am not annoyed 👍 

To be honest, my IDE automatically add and separate the imports 😅 But thanks for trying to replicate it and adding them nicely. 👍

2022-11-15 08:53 UTC, merged