Remove auth null checks in `ExerciseController` methods
mepox/fitbuddy pull request #90
Opened 2022-11-09 10:50 UTC by dmitriydb

## Summary 

## Close issue(s) 
Close #83

2022-11-09 11:18 UTC, mepox commented
Hi @dmitriydb ! Thanks for your contribution. I see you committed both changes into this PR. This is fine for now as both tasks were small. I will close the other PR #91.

2022-11-09 11:35 UTC, dmitriydb commented
> Hi @dmitriydb ! Thanks for your contribution. I see you committed both changes into this PR. 

Hi. Sorry, it was unintentional. 
I merged the first issue branch into my main branch before branching into another issue.

I'm glad it's okay, will be more careful next time

2022-11-09 12:14 UTC, mepox commented
> > Hi @dmitriydb ! Thanks for your contribution. I see you committed both changes into this PR.
> 
> @mepox Hi. Sorry, it was unintentional. I merged the first issue branch into my main branch before branching into another issue.
> 
> I'm glad it's okay, will be more careful next time

@dmitriydb No worries 👍 I will submit a review in the next few minutes.

2022-11-09 12:19 UTC, mepox commented on src/main/java/com/laszlojanku/fitbuddy/operation/controller/ExerciseController.java
>  	}
Indentation from Line 48

2022-11-09 12:19 UTC, mepox commented on src/main/java/com/laszlojanku/fitbuddy/operation/controller/ExerciseController.java
>  	}
Indentation

2022-11-09 12:21 UTC, mepox commented on src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java
>  	}
Indentation

2022-11-09 12:25 UTC, mepox commented on src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java
>  			try {
Indentation

2022-11-09 12:29 UTC, mepox commented on src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java
>  			} catch (DateTimeParseException e) {
Indentation

2022-11-09 12:37 UTC, mepox requested changes
@dmitriydb Thanks again for your work. The code in the PR looks good, but as you have removed some if statments completely, you missed to adjust the indentations. 

Indentations are does not matter in Java (comparing to some other languages) for code "runability", but it's good for code readability.

I left some comments above where I found the indentations are not correct. Could you please fix those? Once that done, this PR will be merged. 👍

2022-11-10 04:52 UTC, dmitriydb commented
Hello again @mepox 
Sorry, I'm a little bit confused now. 
Firstly I made auto lines indentation (usually I'm doing it by pressing a hotkey in my IDE, it's a usual routine although I forgot to do it this time after deleting whole lines) both in HistoryController and ExerciseController.
Then I committed it:  [dd954e2](https://github.com/mepox/fitbuddy/pull/90/commits/dd954e2962596dac6e7248b767680e8f67b7d966)
And I saw that it changed the indentation interval sizes in whole source files altogether. 
So I reverted the commit and tried to auto-indent only highlighted methods: [f22ebf5](https://github.com/mepox/fitbuddy/pull/90/commits/f22ebf5eb392bb481c7621ffbd6fa708abe081ae)

I think I have to re-make it from the scratch. Could you please guide me how to better do it, do we have different indentation size settings or something else maybe?

2022-11-10 05:16 UTC, dmitriydb commented
@mepox 

I've prepared another PR that does both things (removing auth null checks and indentation issues)
#99 

Could you please review it?

2022-11-10 10:54 UTC, mepox commented
> Hello again @mepox Sorry, I'm a little bit confused now. Firstly I made auto lines indentation (usually I'm doing it by pressing a hotkey in my IDE, it's a usual routine although I forgot to do it this time after deleting whole lines) both in HistoryController and ExerciseController. Then I committed it: [dd954e2](https://github.com/mepox/fitbuddy/pull/90/commits/dd954e2962596dac6e7248b767680e8f67b7d966) And I saw that it changed the indentation interval sizes in whole source files altogether. So I reverted the commit and tried to auto-indent only highlighted methods: [f22ebf5](https://github.com/mepox/fitbuddy/pull/90/commits/f22ebf5eb392bb481c7621ffbd6fa708abe081ae)
> 
> I think I have to re-make it from the scratch. Could you please guide me how to better do it, do we have different indentation size settings or something else maybe?

Hi @dmitriydb ! You made a good job to try to fix the problem in this PR. Only one method identation wasn't good enough, so you were very close! However to avoid requesting changes again, I accepted your other PR as that was ready to merge.

Re your code formatting question, collaboration and IDE auto code formatters are not the best friends 😅 Why? Well, everyone has different code style/taste and they set up their IDE differently... Some people like identation size 2 others go with 4. Some people like to use tabs but others prefer to use spaces for tabs... 

Best advice is when contributing to a public project is to try and follow the project's code style so your code fits in nicely with the rest. This means either disable/not use the auto code formatter or configure the code formatter to match the project style.

Here we use indentation size 4 with tabs. Maybe I should add this to the docs 🤔 Looking at your code, you are probably using indentation size 2.

2022-11-10 10:55 UTC, closed without merging

2022-11-10 11:21 UTC, dmitriydb commented
@mepox 
Thank you very much for the detailed answer! It is very useful lesson